Add kafka messages consumer to Framework
AliceO2Group/WebUi pull request #2624
Opened 2024-10-10 16:40 UTC by martinboulais

#### I DON'T have JIRA ticket
- [X] explain what this PR does
- [X] test are added
- [ ] documentation is changed or added

Added a class to listen to ECS kafka messages and automatically parse them using protobuf

2025-01-31 08:29 UTC, graduta requested changes

2025-01-31 08:29 UTC, graduta commented on Framework/Backend/protobuf/getWebUiProtoIncludeDir.js
Licence please

2025-01-31 08:29 UTC, graduta commented on Framework/Backend/kafka/KafkaMessagesConsumer.js
> +        await listener(message);
What do you think in case of having lots of listeners, to use `.catch()` and remove the await so that listeners will not await in sequence

2025-01-31 15:15 UTC, martinboulais commented on Framework/Backend/kafka/KafkaMessagesConsumer.js
> +        await listener(message);
Indeed, fixed

2025-01-31 15:15 UTC, martinboulais commented on Framework/Backend/protobuf/getWebUiProtoIncludeDir.js
Added

2025-02-11 12:42 UTC, graduta approved these changes

2025-02-11 12:43 UTC, merged