[OGUI-1556] feat(layout): allow modification of existing layouts via …
AliceO2Group/WebUi pull request #2629
Opened 2024-10-16 11:41 UTC by mariscalromeroalejandro

…JSON file

#### I DON'T have JIRA ticket
- [ ] explain what this PR does
- [ ] if it is new feature explain how plan to use it
- [ ] test are added
- [ ] documentation is changed or added
- [ ] FLP integration tests were ran successful

#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [ ] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [X] PR labels are selected
- [ ] FLP integration tests were ran successful

2024-11-14 14:41 UTC, graduta requested changes
Please have a look at the comments and let me know where it is not clear. We can then have a go together in pair-programming to address the issues

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/view/header.js
> +                }, 'Edit via JSON'),
After clicking on the `Edit via JSON` and the modal appears, I expect the dropdown from the `edit` button to disappear as well.

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/view/header.js
> +              right: '0',
This style properties should be defined in a CSS class in `app.css` or even better reuse the existing ones such as `.dropdown`. See how `info` button of the objects are using this.

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/view/header.js
> +                  onclick: () => openJSONEditModal(model),
```suggestion
                  onclick: () => {
                    model.isUpdateVisible = true;
                  }
```

Functionality is defined in the model and not in the component. You should call directly from your onclick function

2024-11-14 14:41 UTC, graduta commented on QualityControl/test/setup/seeders/qcg-mock-data-template.json
> +    "layouts": [
As a standard in WebUI, we use `2 space` and not `4 space` for tabbing. Please update your VS code setting and revert this file change

2024-11-14 14:41 UTC, graduta commented on QualityControl/test/public/pages/layout-show.test.js
> +  await editLayoutTests(page, timeout, testParent);
Only `test-index` should import other test files. Moreover the `editLayoutTests` are still part of the page layoutShow. Thus, the naming of the test file should provide us with clear information on that.
I would recommend for this scenario to keep them in the same file otherwise I cannot track which test was updated/added/removed.

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/Layout.js
> +  getUpdatedLayout() {
What does `getUpdatedLayout` refer to? What does it update? I see you are using it to display the initial value in the modal. It would be good to improve on the name of the function to suggest that. Something along the lines: `getLayoutInEditJSONStructure` and in the method doc, you mention it removes the IDs from tabs, objects and layout

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/panels/editModal.js
> +        oninput: (e) => model.layout.checkLayoutToUpdate(e.target.value),
I think the validation should happen only when the user clicks to update the layout. Otherwise, if they make changes manually, it will become quite frustrating to constantly see the error message popping up

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/Layout.js
> +  getUpdatedItem() {
I would recommend this method you remove and integrate it where it is used above

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/Layout.js
> +    this.model.services.update = status;
There is no `update` service in QCG. Where does this come from?

2024-11-14 14:41 UTC, graduta commented on QualityControl/public/layout/Layout.js
> +  saveUpdatedItem() {
Why do you duplicate the `save` method instead of using the existing `save` one?

2024-11-14 15:32 UTC, graduta commented on QualityControl/public/layout/Layout.js
> +  saveUpdatedItem() {
I am referring to the fact that you declared a new method `saveUpdatedItem` instead of directly using the `save` one

2024-11-14 15:55 UTC, mariscalromeroalejandro commented on QualityControl/public/layout/panels/editModal.js
> +        oninput: (e) => model.layout.checkLayoutToUpdate(e.target.value),
The behavior of this modal has been copied from the import schema via JSON modal

2024-11-21 14:30 UTC, graduta approved these changes

2024-11-21 14:31 UTC, merged