[OGUI-1578] Added vscode debugging configuration in launch.js
AliceO2Group/WebUi pull request #2667
Opened 2024-11-20 12:06 UTC by Houwie7000

#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [ ] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected
- [ ] FLP integration tests were ran successful

Added vscode debugging configuration in launch.js
.gitignore exception made for .vscode/launch.js.
Added --inspect parameter to npm run dev command to enable node debugging from the browser.

2024-11-20 13:21 UTC, graduta requested changes
Hi, Jasper! Thank you for adding a configuration to quickly start a server in dev mode. Please see my comments on some changes that I think need to be done before approving this PR. 

One more general comment, please make sure to add a new line at the end of the files when you commit. This is checked by the lint process by also by GitHub if you check the files in  your PR changes.(attaching here a small screenshot as well)
![image](https://github.com/user-attachments/assets/5445a6e3-c5e6-4ca5-aa52-e33f0614bfcf)

2024-11-20 13:21 UTC, graduta commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
I believe these comments can be removed

2024-11-20 13:21 UTC, graduta commented on .vscode/launch.json
> +            "name": "Run dev",
As the file for all configurations sits at the root of the directory, it means it covers all 4 GUIs present in this repository. Thus, I would like for the `name` filed of the configurations to be a bit more specific. For example, the one you added is for InfoLogger so the name should inform the developer about it. 
Perhaps a more sensible name would be: `[ilg] run dev`
`[ilg]` stands for InfoLogger GUI and it is a common label used within the team to refer to this project

2024-11-20 13:21 UTC, graduta commented on .vscode/launch.json
> +            "localRoot": "${workspaceFolder}\\InfoLogger\\",
I see that you have used the `Windows` path for localRoot. This of course will not work for unix based operating systems.
Could you please create a configuration for windows and one for unix based systems in which the forward slash is used for the path?
Ideally, the name of the configuration should also reflect this

2024-11-20 23:09 UTC, Houwie7000 commented
I've resolved the feedback, the config now works on *nix like platforms and on Windows.

2024-11-21 10:23 UTC, graduta approved these changes

2024-11-21 10:23 UTC, merged