[OGUI-1472] Run types filter selector for layout show view
AliceO2Group/WebUi pull request #2691
Opened 2024-12-05 15:05 UTC by mariscalromeroalejandro

#### I have JIRA issue created
- [X] branch and/or PR name(s) includes JIRA ID
- [X] issue has "Fix version" assigned
- [X] issue "Status" is set to "In review"
- [X] PR labels are selected
- [ ] FLP integration tests were ran successful

PR which:
* Adds new filter selector for run types in layout show view
* Retrieves run types from bookkeeping
* Creates a filter selector component to be able to reuse it

2025-05-05 13:59 UTC, graduta requested changes

2025-05-05 13:59 UTC, graduta commented on QualityControl/README.md
This might need to be updated based on new DOCS you have written

2025-05-05 13:59 UTC, graduta commented on QualityControl/lib/api.js
> +    jsonFileService, filterController,
Perhaps better on a new line like the others?

2025-05-05 13:59 UTC, graduta commented on QualityControl/lib/api.js
> +  http.get('/runTypes', filterController.getRunTypesHandler.bind(filterController));
Given that they are related to the filter model, I think is best we add something more general which will allow other filter parameters?
`/filter/configuration`. Same for the controller method name

2025-05-05 13:59 UTC, graduta commented on QualityControl/lib/QCModel.js
> +  const filterController = new FilterController(bookkeepingService);
The filter controller should receive a filter service (high-level service) which in the future will build the filter based on other service as well.
The Bookkeeping service should return the data as stored in BKP and the Filter service should be the one mapping the list of runTypes recieved to a list.

2025-05-05 13:59 UTC, graduta commented on QualityControl/lib/controllers/FilterController.js
> +      if (!this._bkpService) {
We should not throw an error but instead return an empty list of run types. Of course, the logic being in the FIlter Service

2025-05-05 13:59 UTC, graduta commented on QualityControl/lib/services/BookkeepingService.js
> +    if (!this._hostname || !this._port || !this._protocol) {
It is important to notice that our URLs are not always in the format `hostname:port`, but sometimes is just a simple URL like `alice-bkp.cern.ch`
Thus, you should not throw an error if you cannot export the port but instead modify the `httpGetJson` method to be able to make a request even if you pass just a URL instead of hostname and port. 
It is standard convention that for HTTPS port is 443 and HTTP is 80

2025-05-07 12:52 UTC, graduta requested changes
A few minor comments but after that looks good

2025-05-07 12:52 UTC, graduta commented on QualityControl/docs/Configuration.md
> +Attribute to define the `Bookkeeping` endpoint.
Missing attribute that encapsulates the attributes below. Perhaps providing an example object can help (with non-existent URL and token)

2025-05-07 12:52 UTC, graduta commented on QualityControl/lib/QCModel.js
> +import { FilterService } from './services/FilterService.js';
Please import the FilterService in the services categories (grouped by lines above around line 26)

2025-05-07 12:52 UTC, graduta commented on QualityControl/lib/controllers/FilterController.js
> +     * @type {BookkeepingService}
Wrong type

2025-05-07 12:52 UTC, graduta commented on QualityControl/lib/controllers/FilterController.js
> +  constructor(filterService) {
Missing docs for constructor

2025-05-07 12:52 UTC, graduta commented on QualityControl/lib/services/FilterService.js
> +    assert(bookkeepingService, 'Bookkeeping Service is required');
Given that you have the check in controller, there is no point in keeping it here as assert will throw an error if missing. Remember, filter service will incorporate multiple components and bookkeeping will not be a critical one

2025-05-07 12:52 UTC, graduta commented on QualityControl/test/lib/controllers/FiltersController.test.js
> +      const bkpService = {
I believe this is the filter service now which you can mock with class definition with SInon so that is even more self-explanatory

2025-05-07 12:52 UTC, graduta commented on QualityControl/test/lib/controllers/FiltersController.test.js
> +    test('should return an empty array if bookkeeping service is not defined', async () => {
Could you add a test in case BKP is configured by replies with error?

2025-05-07 12:52 UTC, graduta commented on QualityControl/test/public/pages/layout-show.test.js
> +  // await testParent.test(
Will this be enabled? If not, it should be removed

2025-05-07 12:52 UTC, graduta commented on QualityControl/public/common/filters/filterTypes.js
> +const FILTER_TYPE = {
I believe the convention we are aiming for is:
```
const FilterType = {
  INPUT: 'input',
  DROPDOWN: 'dropdownSelector',
};
```

2025-05-07 12:52 UTC, graduta commented on QualityControl/public/common/filters/filter.js
> +import { RemoteData } from '/js/src/index.js';
h and RemoteData can be imported together

2025-05-07 12:52 UTC, graduta commented on QualityControl/public/layout/Layout.js
> +    if (value) {
If value is a number and contains value `0` this will not pass and delete the filter. You should specifically check for undefined/null. In this way with values of 0 or empty strings will pass

2025-05-07 12:52 UTC, graduta commented on QualityControl/lib/services/BookkeepingService.js
> +const logger = LogManager.getLogger(`${process.env.npm_config_log_label ?? 'bkp'}/service`);
For loggers, we try to add a label to specify which services it is. Thus instead of `/service`, we would use `/bkp-service`

2025-05-07 12:52 UTC, graduta commented on QualityControl/public/layout/view/panels/filtersConfig.js
> +    placeholder: 'RunType (e.g. PHYSICS)',
I think given that is a dropdown, we should use `ANY` as placeholder.
Placeholders on dropdown elements are not displayed like on the input ones with a light grey but instead it looks like selected option.

2025-05-07 12:52 UTC, graduta commented on QualityControl/public/Model.js
> +    this.services.filter.initFilterService();
I believe the services are currently initiliazed in handleLocationChange. It would be good if you initialize that one there as well https://github.com/AliceO2Group/WebUi/pull/2691/files#diff-8829298f0249abbf3900a4d93c5d0d84fc5bb4e38bfcd19be06a9d0b42657522R177

2025-05-07 12:52 UTC, graduta commented on QualityControl/public/layout/view/panels/filters.js
> +        filterElement = dynamicSelector({ ...commonConfig, options, onChangeCallback }); break;
Missing new line before `break`

2025-05-07 13:23 UTC, graduta commented on QualityControl/public/common/filters/filter.js
> +  return h(`${width}`, [
You are missing the `.` in front of the class. 
Like you wrote it, it will create an HTML element w-20 
```html
<w-20></w-20>
```
(the same goes for the dropdown selector

2025-05-08 10:10 UTC, mariscalromeroalejandro commented on QualityControl/test/lib/controllers/FiltersController.test.js
> +    test('should return an empty array if bookkeeping service is not defined', async () => {
this test case is checked by filter service. The controller should not be aware of this

2025-05-08 10:29 UTC, graduta approved these changes

2025-05-08 11:24 UTC, merged