[OGUI-665] Add button to each task to redirect to Mesos
AliceO2Group/WebUi pull request #680
Opened 2021-02-01 14:53 UTC by graduta

#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

PR which:
* brings locked column in line with `Tasks` page and icons are used to show the state
* adds a new column to the Tasks table of each environment. This will allow the user to open a new page with Mesos logs for that specific task

﻿
<img width="1426" alt="Screenshot 2021-02-01 at 16 49 38" src="https://user-images.githubusercontent.com/9214854/106474812-f3f56e80-64ad-11eb-97da-9564bc085d51.png">

2021-02-01 15:38 UTC, awegrzyn requested changes
If I'm not mistaken all URLs use TaskID of first task

2021-02-01 15:47 UTC, graduta commented
> If I'm not mistaken all URLs use TaskID of first task

URL is used directly from `core` without modification. I checked now and indeed all 3 of them have the same mesos URL so if they should be different, we will need to look at `core`

Moreover, the 3 tasks have the following IDs:
* `2P2WT341zwE`
* `2P2WT341KyN`
* `2P2WT341fTJ`

The mesos built URL contains no such IDs

2021-02-02 11:48 UTC, graduta commented
Following the update of the requirements, PR has been updated accordingly

2021-02-04 07:45 UTC, awegrzyn approved these changes

2021-02-04 07:49 UTC, merged