[OGUI-829] Pass run variable to Grafana when loading environment monitoring panels
AliceO2Group/WebUi pull request #727
Opened 2021-04-15 08:18 UTC by awegrzyn

#### I have JIRA issue created
- [x] branch and/or PR name(s) includes JIRA ID
- [ ] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected
- [ ] FLP integration tests were ran successful

2021-04-15 08:35 UTC, graduta requested changes

2021-04-15 09:09 UTC, graduta approved these changes

2021-04-16 08:22 UTC, graduta commented
Hi @awegrzyn ,
As this is a change that needs to be in line with a change in monitoring, thus nothing being broken as of now. 
Should this be a minor version bump rather than a patch?

2021-04-16 08:24 UTC, awegrzyn commented
It does not need to be in line, it does no break anything, it's backward and forward compatible.

2021-04-16 08:29 UTC, merged